# Foraging test configuration
# 10x10 world with multiple entities competing for berry bushes

[world]
width = 10
height = 10
tick_duration_ms = 1000

[[entities]]
id = "alice"
type = "player"
x = 2
y = 2

[[entities]]
id = "bob"
type = "player"
x = 8
y = 8

[[objects]]
id = "bush1"
type = "bush"
x = 3
y = 3
berry_count = 5
max_berries = 5

[[objects]]
id = "bush2"
type = "bush"
x = 7
y = 7
berry_count = 5
max_berries = 5

[[objects]]
id = "bush3"
type = "bush"
x = 5
y = 5
berry_count = 5
max_berries = 5
